### ISSUE TITLE
v1.1.1 ready?

### ISSUE THREAD

**Issue by marklit** [Query-farm/lindel#2]
```sql
INSTALL lindel FROM community;
```

```
HTTP Error: Failed to download extension "lindel" at URL "http://community-extensions.duckdb.org/v1.1.1/linux_amd64_gcc4/lindel.duckdb_extension.gz" (HTTP 403)
```

**Comment by rustyconover** [comment]
Hey @marklit 

I'll have a new version released shortly just need to bump the settings in the CI.

Rusty

**Comment by carlopi** [comment]
Hi! We will iterate on the community extensions to have them built in the next few hours

**Comment by carlopi** [comment]
Some more context: https://github.com/duckdb/community-extensions/pull/124#issuecomment-2371138273

**Comment by carlopi** [comment]
Build is done, just checked and it does work now on my side:
```sql
INSTALL lindel FROM community;
```

**Comment by marklit** [comment]
Works from here too. Thank you very much.
